project:
  type: website

website:
  favicon: images/favicon.ico
  #title: "CAPB_web"
  back-to-top-navigation: true
  navbar:
    logo: "images/logos/Panorama.png"
    logo-alt: "Dreal-NA-Logements-vacants"
    collapse-below: xxl
    left:
      - href: index.qmd
        icon: house
        text: Accueil
        
      - text: Annexes
        icon: folder
        menu:
          - href: annexe1.qmd
            text: "Annexe 1 : LOVAC"
          - href: annexe2.qmd
            text: "Annexe 2 : liste des communes cartographiées (IRIS)"
          - href: annexe3.qmd
            text: "Annexe 3 : Définition du Zonage"
          

      - text: Cartographie des logements vacants
        icon: map
        menu:
          - href: epci.qmd
            text: EPCI
          - href: communes.qmd
            text: Communes
          - href: iris.qmd
            text: IRIS
            
      - icon: file-earmark-text
        href: documents.qmd
        text: Documents à télécharger

      - text: Qui Sommes nous ?
        icon: people-fill
        menu:
          - href: presentation_dreal.qmd
            text: DREAL Nouvelle-Aquitaine
          - href: presentation_cerema.qmd
            text: Cerema
      
  page-footer:
    left: "Site créé avec [Quarto](https://quarto.org/)"
    center: "©CEREMA"
    right: 
      - icon: linkedin
        href: https://fr.linkedin.com/company/cerema
      - icon: twitter-x 
        href: https://x.com/ceremacom
      - icon: youtube
        href: https://www.youtube.com/@cerema3139 

format:
  html:
    theme: [flatly, custom.scss]
    toc: true
    toc-title: Contenu
    toc-location: left
    toc-depth: 3
    html-embed: true
    include-in-header: assets/header.html
    navbar-html: true

editor: visual


