---
title: ""
format: html
editor: visual
lang: fr
lightbox: true
toc: false
---

## ANNEXE 2 : liste des communes cartographiées pour la vacance au quartier IRIS  

<div style="text-align:center; display:flex; flex-direction:column; align-items:center; gap:8px;">
  <p style="margin:0;">Communes cartographiées par département</p>
  <p style="margin:0;">Source : Cerema – CARTES IRIS PAR DEPARTEMENT</p>
</div>


| Département              | Commune                    | N° |
|--------------------------|----------------------------|----|
| Charente                 | Angoulême                  | 1  |
| Charente                 | Barbezieux-Saint-Hilaire   | 2  |
| Charente                 | Cognac                     | 3  |
| Charente-Maritime        | Rochefort                  | 4  |
| Charente-Maritime        | La Rochelle                | 5  |
| Charente-Maritime        | Royan                      | 6  |
| Charente-Maritime        | Saintes                    | 7  |
| Charente-Maritime        | Saujon                     | 8  |
| Charente-Maritime        | Saint-Jean-d’Angély        | 9  |
| Charente-Maritime        | Saint-Pierre-d’Oléron      | 10 |
| Charente-Maritime        | Surgères                   | 11 |
| Corrèze                  | Brive-la-Gaillarde         | 12 |
| Corrèze                  | Tulle                      | 13 |
| Corrèze                  | Ussel                      | 14 |
| Creuse                   | Aubusson                   | 15 |
| Creuse                   | Guêret                     | 16 |
| Creuse                   | La Souterraine             | 17 |
| Dordogne                 | Bergerac                   | 18 |
| Dordogne                 | Montpon-Ménestérol         | 19 |
| Dordogne                 | Périgueux                  | 20 |
| Dordogne                 | Sarlat-la-Canéda           | 21 |
| Dordogne                 | Terrasson-Lavilledieu      | 22 |
| Gironde                  | Bègles                     | 23 |
| Gironde                  | Le Bouscat                 | 24 |
| Gironde                  | Bordeaux                   | 25 |
| Gironde                  | Cenon                      | 26 |
| Gironde                  | Coutras                    | 27 |
| Gironde                  | Gradignan                  | 28 |
| Gironde                  | Langon                     | 29 |
| Gironde                  | Libourne                   | 30 |
| Gironde                  | Lormont                    | 31 |
| Gironde                  | Mérignac                   | 32 |
| Gironde                  | Pauillac                   | 33 |
| Gironde                  | Pessac                     | 34 |
| Gironde                  | Saint-André-de-Cubzac      | 35 |
| Gironde                  | Saint-Médard-en-Jalles     | 36 |
| Gironde                  | Talence                    | 37 |
| Gironde                  | Villenave-d’Ornon          | 38 |
| Landes                   | Aire-sur-l’Adour           | 39 |
| Landes                   | Dax                        | 40 |
| Landes                   | Mont-de-Marsan             | 41 |
| Lot-et-Garonne           | Agen                       | 42 |
| Lot-et-Garonne           | Fumel                      | 43 |
| Lot-et-Garonne           | Marmande                   | 44 |
| Lot-et-Garonne           | Tonneins                   | 45 |
| Lot-et-Garonne           | Villeneuve-sur-Lot         | 46 |
| Pyrénées-Atlantiques     | Anglet                     | 47 |
| Pyrénées-Atlantiques     | Bayonne                    | 48 |
| Pyrénées-Atlantiques     | Biarritz                   | 49 |
| Pyrénées-Atlantiques     | Hasparren                  | 50 |
| Pyrénées-Atlantiques     | Hendaye                    | 51 |
| Pyrénées-Atlantiques     | Mauléon                    | 52 |
| Pyrénées-Atlantiques     | Mourenx                    | 53 |
| Pyrénées-Atlantiques     | Oloron-Sainte-Marie        | 54 |
| Pyrénées-Atlantiques     | Orthez                     | 55 |
| Pyrénées-Atlantiques     | Pau                        | 56 |
| Deux-Sèvres              | Bressuire                  | 57 |
| Deux-Sèvres              | Niort                      | 58 |
| Deux-Sèvres              | Parthenay                  | 59 |
| Deux-Sèvres              | Saint-Maixent-l’Ecole      | 60 |
| Deux-Sèvres              | Thouars                    | 61 |
| Vienne                   | Chauvigny                  | 62 |
| Vienne                   | Châtellerault              | 63 |
| Vienne                   | Loudun                     | 64 |
| Vienne                   | Montmorillon               | 65 |
| Vienne                   | Poitiers                   | 66 |
| Haute-Vienne             | Bellac                     | 67 |
| Haute-Vienne             | Limoges                    | 68 |
| Haute-Vienne             | Saint-Junien               | 69 |
| Haute-Vienne             | Saint-Yrieix-la-Perche     | 70 |

Total : 70 communes.