---
title: ""
format: html
editor: visual
lang: fr
lightbox: true
toc: false
---

## ANNEXE 1 : LOVAC
::: {style="font-family: YACkoD1yZN0-0;font-size:1.1em;"}
Les données LOVAC sont les données les plus précises et les plus fiables dont disposent les collectivités pour lutter contre les logements vacants à ce jour. Ce sont des données opérationnelles produites chaque année par le Cerema (existent depuis la mise en œuvre du plan national de lutte contre les logements vacants).  

Les données LOVAC sont issues de sources fiscales **(ces sources comme les méthodes ont varié selon les millésimes). Par exemple, le millésime 2025 de LOVAC (sur l’année 2024) est issu du croisement :**  

<div style="padding-left: 25px;">
• des informations du **fichier 1767BISCOM**, produit par la DGFiP,  
• enrichies par des informations des **Fichiers fonciers**, issues du fichier MAJIC, produit par la DGFiP.  
• des informations de **DV3F**, issues du fichier Demande de Valeurs Foncières, produit par la DGFiP,  
• complétées par la **Base Adresse Nationale** (BAN), référentiel produit par l'IGN et la DINUM.  
</div>  

Les données LOVAC 2023 à 2025 utilisent les déclaration des propriétaires via **Gérer Mes Biens Immobiliers** (GMBI) : les propriétaires remplissent le statut d’occupation de leurs biens dont la potentielle vacance.

GMBI a été mis en place en 2021 et généralisé en 2023 (les 3/4 des propriétaires avaient rempli cette obligation en 2023, le taux s’améliore depuis). GMBI a été mis en place suite à la suppression de la taxe d’habitation (2023), entraînant la disparition des données fiscales collectées en vue de cette taxation qui étaient **essentielles à l’identification de l'ensemble des statuts d’occupation du parc de logements** (résidences principales, résidences secondaires et les logements vacants).

Les donnés LOVAC sur les années antérieures à 2023 (taxe d’habitation) sont donc très différentes des données post 2024. La méthode de collecte LOVAC a également évolué : il n’est pas non plus pertinent de comparer les millésimes 2026, 2025 et 2024 sur les années 2025, 2024 et 2023.
:::